Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: sns-slack-publish-abstract
    Description: Publish AWS SNS messages to Slack with abstracted Template
    Author: sufiyanpk7 fouzankv
    SpdxLicenseId: MIT
    LicenseUrl: ./LICENSE
    ReadmeUrl: ./README.md
    Labels: [ 'sns', 'slack', 'nodejs', 'cloudwatch']
    HomePageUrl: https://github.com/sufiyanpk7/sns-slack-publish-formatted/tree/feature/abstractTemplate
    SemanticVersion: 0.1.1
    SourceCodeUrl: https://github.com/sufiyanpk7/sns-slack-publish-formatted/tree/feature/abstractTemplate

Parameters:
    SlackUrl:
        Type: String
    TopicArn:
        Type: String
    ClentName:
        Type: String
        Default: ClientName

Resources:

  Function:
    Type: AWS::Serverless::Function
    Properties:
        FunctionName: !Sub "${AWS::StackName}"
        Runtime: nodejs16.x
        Handler: post.handler
        CodeUri: ./app
        Environment:
            Variables:
              URL: !Ref SlackUrl
              CLIENT: !Ref ClentName
        Events:
            Message:
                Type: SNS
                Properties:
                    Topic: !Ref TopicArn